### ISSUE TITLE
Jana Mocková se nemůže přihlásit

### ISSUE THREAD

**Issue by wonderwayofj** [extropysk/dobyhory.sk#2]
mocajana@seznam.cz

Jana Mocková

paní zadává tento mail a heslo "hory" a nefunguje to. Vygeneruj prosím nové heslo a zkontroluj, jestli vše sedí u tohoto mailu. :)

**Comment by kristianduda** [comment]
Heslo nastavene na "hory1234". Skusil som sa prihlasit, vsetko vyzera v poriadku.
